# Generated by Django 3.2.8 on 2022-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', 'dollar'), ('#', 'naira'), ('€', 'euro'), ('£', 'pound')], default='naira', max_length=10),
        ),
    ]
